//! PQ-hybrid DTLS-SRTP handshake glue.
//!
//! Owns the ephemeral ML-KEM-768 keypair that gets used for one call.
//! The DTLS handshake itself is driven by the vendored `webrtc-dtls`
//! transport (landing in Phase D); this module sits next to it and
//! provides the PQ secret that gets folded into the SRTP key
//! derivation per the construction in
//! `scratch/pq-dtls-srtp-construction.md`.
//!
//! Phase B scope: type definitions + the ML-KEM-768 keygen / encap /
//! decap helpers. The DTLS exporter extraction and SRTP context
//! construction still wait for Phase D + E.

// Crypto convention uses short paired names like pk/sk and ek/dk; clippy's
// `similar_names` complains, but renaming them to dissimilar identifiers
// hurts readability for anyone reading the cryptographic literature.
#![allow(clippy::similar_names)]

use std::sync::Arc;

use dtls::config::{ClientAuthType, Config as DtlsConfig, ExtendedMasterSecretType};
use dtls::conn::DTLSConn;
use dtls::crypto::Certificate;
use dtls::extension::extension_use_srtp::SrtpProtectionProfile;
use ml_kem::kem::{Decapsulate, Encapsulate};
use ml_kem::{EncodedSizeUser, KemCore, MlKem768};
use rand::rngs::OsRng;
use rand_core::{CryptoRng, RngCore};
use tracing::instrument;
use webrtc_util::{Conn, KeyingMaterialExporter};
use zeroize::Zeroize;

use crate::call::Role;
use crate::constants::{DTLS_EXPORTER_LEN, DTLS_SRTP_EXPORTER_LABEL};
use crate::error::MediaError;

/// Ephemeral PQ key material for a single call.
///
/// Generated by the caller during `CallInvite` construction. The
/// public key is sent to the callee in the invite payload; the
/// secret key never leaves the calling device. Zeroized on drop.
#[derive(Zeroize)]
#[zeroize(drop)]
pub struct PqHandshakeKeypair {
    /// ML-KEM-768 encapsulation key (public). 1184 bytes.
    pub encapsulation_key: Vec<u8>,
    /// ML-KEM-768 decapsulation key (secret). 2400 bytes.
    pub decapsulation_key: Vec<u8>,
}

/// Output of the ML-KEM-768 encapsulation step performed by the callee
/// in response to a `CallInvite`.
///
/// `ciphertext` is sent back inside a `CallAccept`; `shared_secret` is
/// retained locally and fed into the SRTP master KDF together with the
/// DTLS exporter once the handshake completes.
pub struct PqEncapsulation {
    /// ML-KEM-768 ciphertext. 1088 bytes.
    pub ciphertext: Vec<u8>,
    /// 32-byte shared secret. Folded into the SRTP master KDF.
    pub shared_secret: PqSharedSecret,
}

/// Resolved-by-both-sides PQ shared secret after one full round trip
/// (caller encap-key → callee encap → callee ciphertext → caller decap).
///
/// Wrapped in a newtype so it cannot be accidentally logged or
/// serialized; consumers that need the raw bytes go through
/// [`PqSharedSecret::expose`].
#[derive(Zeroize)]
#[zeroize(drop)]
pub struct PqSharedSecret([u8; 32]);

impl PqSharedSecret {
    /// Length of the shared secret, in bytes.
    pub const LEN: usize = 32;

    /// Construct from raw bytes. Internal-only; call sites are
    /// [`encapsulate`] and [`decapsulate`]. Tests and the SRTP
    /// master-derivation unit tests in `srtp.rs` use this to pin
    /// known values without standing up a real KEM round trip.
    #[must_use]
    pub(crate) const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Expose the raw bytes for the HKDF input. Caller is responsible
    /// for not leaking them — log prefixes only per the global
    /// "never log key material" rule.
    #[must_use]
    pub const fn expose(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Generate a fresh ML-KEM-768 keypair for one call. Driven by [`OsRng`].
///
/// # Errors
///
/// Returns [`MediaError::PqKex`] only on an impossible underlying RNG
/// failure (the `ml-kem` crate's `generate` is infallible against a
/// real OS RNG).
#[instrument(level = "debug")]
pub fn generate_keypair() -> Result<PqHandshakeKeypair, MediaError> {
    generate_keypair_from_rng(&mut OsRng)
}

/// Generate an ML-KEM-768 keypair from an explicit RNG. Useful for
/// deterministic tests with a seeded RNG.
///
/// # Errors
///
/// Same as [`generate_keypair`].
#[instrument(level = "debug", skip(rng))]
pub fn generate_keypair_from_rng<R: CryptoRng + RngCore>(
    rng: &mut R,
) -> Result<PqHandshakeKeypair, MediaError> {
    let (decap_key, encap_key) = MlKem768::generate(rng);
    let kp = PqHandshakeKeypair {
        encapsulation_key: encap_key.as_bytes().to_vec(),
        decapsulation_key: decap_key.as_bytes().to_vec(),
    };
    tracing::debug!(
        ek_len = kp.encapsulation_key.len(),
        dk_len = kp.decapsulation_key.len(),
        "ml-kem-768 keypair generated for call"
    );
    Ok(kp)
}

/// Encapsulate to the caller's ML-KEM-768 public key. Run by the
/// **callee** when processing a `CallInvite`. Produces the ciphertext
/// to send back in the `CallAccept` plus the shared secret to retain
/// locally for SRTP key derivation.
///
/// # Errors
///
/// Returns [`MediaError::PqKex`] if the public key is malformed
/// (wrong length / not a valid encapsulation key) or if the
/// underlying `ml-kem` encap fails.
#[instrument(level = "debug", skip(caller_ek))]
pub fn encapsulate(caller_ek: &[u8]) -> Result<PqEncapsulation, MediaError> {
    encapsulate_with_rng(caller_ek, &mut OsRng)
}

/// Encapsulate with an explicit RNG. Test-only helper.
///
/// # Errors
///
/// Same as [`encapsulate`].
#[instrument(level = "debug", skip(caller_ek, rng))]
pub fn encapsulate_with_rng<R: CryptoRng + RngCore>(
    caller_ek: &[u8],
    rng: &mut R,
) -> Result<PqEncapsulation, MediaError> {
    let ek_bytes: &ml_kem::Encoded<<MlKem768 as KemCore>::EncapsulationKey> = caller_ek
        .try_into()
        .map_err(|_| MediaError::PqKex("encapsulation key wrong length".into()))?;
    let ek = <MlKem768 as KemCore>::EncapsulationKey::from_bytes(ek_bytes);

    let (ct, ss) = ek
        .encapsulate(rng)
        .map_err(|e| MediaError::PqKex(format!("ml-kem encapsulate: {e:?}")))?;

    let mut ss_bytes = [0u8; 32];
    ss_bytes.copy_from_slice(&ss);

    Ok(PqEncapsulation {
        ciphertext: ct.to_vec(),
        shared_secret: PqSharedSecret::from_bytes(ss_bytes),
    })
}

/// Decapsulate the callee's response. Run by the **caller** when
/// processing a `CallAccept`. Recovers the same shared secret the
/// callee derived.
///
/// # Errors
///
/// Returns [`MediaError::PqKex`] if the decap key or ciphertext is
/// malformed.
#[instrument(level = "debug", skip(caller_dk, ciphertext))]
pub fn decapsulate(caller_dk: &[u8], ciphertext: &[u8]) -> Result<PqSharedSecret, MediaError> {
    let dk_bytes: &ml_kem::Encoded<<MlKem768 as KemCore>::DecapsulationKey> = caller_dk
        .try_into()
        .map_err(|_| MediaError::PqKex("decapsulation key wrong length".into()))?;
    let dk = <MlKem768 as KemCore>::DecapsulationKey::from_bytes(dk_bytes);

    let ct_bytes: &ml_kem::Ciphertext<MlKem768> = ciphertext
        .try_into()
        .map_err(|_| MediaError::PqKex("ciphertext wrong length".into()))?;
    let ss = dk
        .decapsulate(ct_bytes)
        .map_err(|e| MediaError::PqKex(format!("ml-kem decapsulate: {e:?}")))?;

    let mut ss_bytes = [0u8; 32];
    ss_bytes.copy_from_slice(&ss);

    Ok(PqSharedSecret::from_bytes(ss_bytes))
}

/// 60-byte DTLS-SRTP exporter output, wrapped to zeroize on drop.
///
/// Produced by [`extract_dtls_exporter`] from a completed DTLS
/// handshake. Feed into [`crate::srtp::derive_srtp_master`] together
/// with a [`PqSharedSecret`] to obtain the PQ-folded SRTP master.
///
/// Length is fixed at [`DTLS_EXPORTER_LEN`] so calls into the
/// derivation cannot accidentally truncate or pad it.
#[derive(Zeroize)]
#[zeroize(drop)]
pub struct DtlsExporter([u8; DTLS_EXPORTER_LEN]);

impl DtlsExporter {
    /// Length of the exporter output, in bytes.
    pub const LEN: usize = DTLS_EXPORTER_LEN;

    /// Borrow the raw bytes. Caller is responsible for not leaking
    /// them — only the HKDF derivation in [`crate::srtp`] should ever
    /// touch this directly.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; DTLS_EXPORTER_LEN] {
        &self.0
    }
}

/// Extract 60 bytes of RFC 5705 keying material from a completed
/// DTLS connection.
///
/// Drives `connection_state().await.export_keying_material(...)`
/// from the `webrtc-rs` `dtls` crate. Generic over the
/// `KeyingMaterialExporter` trait so tests can drive it without a
/// real DTLS handshake; production call sites pass a
/// `dtls::state::State` cloned via
/// `dtls::conn::DTLSConn::connection_state()`.
///
/// **Zeroize caveat:** `dtls::state::State` does **not** implement
/// `ZeroizeOnDrop` as of webrtc-rs 0.17.1. The caller is responsible
/// for ensuring the cloned `State` (which carries `master_secret`)
/// is dropped promptly. The 60-byte output here is wrapped in a
/// zeroize-on-drop newtype so once it lands in [`DtlsExporter`]
/// further handling is safe. Tracked as M7-followup.
///
/// # Errors
///
/// Returns [`MediaError::DtlsHandshake`] if the exporter fails (most
/// commonly because the handshake hasn't completed yet) or returns
/// a length that doesn't match [`DTLS_EXPORTER_LEN`].
#[instrument(level = "debug", skip(exporter))]
pub async fn extract_dtls_exporter<E: KeyingMaterialExporter + Sync>(
    exporter: &E,
) -> Result<DtlsExporter, MediaError> {
    let mut raw = exporter
        .export_keying_material(DTLS_SRTP_EXPORTER_LABEL, &[], DTLS_EXPORTER_LEN)
        .await
        .map_err(|e| MediaError::DtlsHandshake(format!("export_keying_material: {e}")))?;

    if raw.len() != DTLS_EXPORTER_LEN {
        // Zeroize the wrong-length buffer too before discarding.
        raw.zeroize();
        return Err(MediaError::DtlsHandshake(format!(
            "exporter returned bytes, expected {DTLS_EXPORTER_LEN}",
        )));
    }

    let mut buf = [0u8; DTLS_EXPORTER_LEN];
    buf.copy_from_slice(&raw);

    // Best-effort zeroize of the heap-allocated intermediate. The
    // webrtc-rs trait returns a fresh Vec<u8> — we don't own the
    // underlying allocation, but we can overwrite the bytes before
    // drop. After this point only `buf` carries the secret, and it
    // moves into a zeroize-on-drop newtype below.
    raw.zeroize();

    tracing::debug!(len = DTLS_EXPORTER_LEN, "dtls exporter extracted");
    Ok(DtlsExporter(buf))
}

/// Build a DTLS config suitable for Lattice voice/video.
///
/// Pins:
/// - One self-signed cert with `lattice` as the subject alt name (the
///   real binding is via MLS-attested identity, not DTLS certs;
///   `insecure_skip_verify = true` is therefore safe at the DTLS
///   layer alone).
/// - SRTP protection profile = AES-128-GCM (RFC 7714) preferred,
///   AES-128-CM-HMAC-SHA1-80 as fallback. Both lay session keys out
///   at the same 60-byte layout we derive in
///   [`crate::srtp::derive_srtp_master`].
/// - Extended master secret REQUIRED — defends against the
///   triple-handshake attack and is universally supported by modern
///   DTLS stacks.
///
/// # Errors
///
/// Returns [`MediaError::DtlsHandshake`] if rcgen fails to mint the
/// self-signed cert (essentially never).
pub fn default_dtls_config() -> Result<DtlsConfig, MediaError> {
    let cert = Certificate::generate_self_signed(vec!["lattice".to_string()])
        .map_err(|e| MediaError::DtlsHandshake(format!("generate_self_signed: {e}")))?;
    Ok(DtlsConfig {
        certificates: vec![cert],
        srtp_protection_profiles: vec![
            SrtpProtectionProfile::Srtp_Aead_Aes_128_Gcm,
            SrtpProtectionProfile::Srtp_Aes128_Cm_Hmac_Sha1_80,
        ],
        extended_master_secret: ExtendedMasterSecretType::Require,
        // MLS attests the peer's identity end-to-end; certificate-layer
        // verification at DTLS is redundant and would force a CA
        // hierarchy we don't have. Skip is safe here ONLY because the
        // call-invite signature in `CallInvite.sig` cryptographically
        // binds the DTLS handshake to the MLS-verified caller identity.
        insecure_skip_verify: true,
        // Mutual cert auth at the DTLS layer is meaningless under
        // Lattice's threat model (MLS attests both ends end-to-end),
        // so the server doesn't demand a client cert. Setting this
        // to `RequireAnyClientCert` would force `WebPkiClientVerifier`
        // even with `insecure_skip_verify = true`, which fails with an
        // empty `client_cas`.
        client_auth: ClientAuthType::NoClientCert,
        ..DtlsConfig::default()
    })
}

/// Drive a DTLS handshake over a connected ICE `Conn`.
///
/// Returns the connected `DTLSConn` ready for
/// [`extract_dtls_exporter`] / `write` / `read`. The caller chose
/// the [`Role`] from the surrounding call state (the caller is the
/// DTLS client, the callee is the DTLS server).
///
/// # Errors
///
/// Returns [`MediaError::DtlsHandshake`] on any handshake failure
/// (cert validation, transport, timeout, etc.).
#[instrument(level = "debug", skip(transport, config))]
pub async fn negotiate_dtls(
    transport: Arc<dyn Conn + Send + Sync>,
    role: Role,
    config: DtlsConfig,
) -> Result<DTLSConn, MediaError> {
    let is_client = matches!(role, Role::Caller);
    DTLSConn::new(transport, config, is_client, None)
        .await
        .map_err(|e| MediaError::DtlsHandshake(format!("dtls negotiate ({role:?}): {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use async_trait::async_trait;
    use rand::SeedableRng;
    use webrtc_util::{KeyingMaterialExporterError, KeyingMaterialExporter as Kme};

    #[test]
    fn keygen_returns_canonical_sizes() {
        let kp = generate_keypair().expect("keygen");
        assert_eq!(kp.encapsulation_key.len(), 1184, "ml-kem-768 ek is 1184 B");
        assert_eq!(kp.decapsulation_key.len(), 2400, "ml-kem-768 dk is 2400 B");
    }

    #[test]
    fn encap_returns_canonical_ciphertext_size() {
        let kp = generate_keypair().expect("keygen");
        let enc = encapsulate(&kp.encapsulation_key).expect("encap");
        assert_eq!(enc.ciphertext.len(), 1088, "ml-kem-768 ct is 1088 B");
        assert_eq!(enc.shared_secret.expose().len(), 32, "ml-kem-768 ss is 32 B");
    }

    #[test]
    fn encap_decap_round_trip_agrees() {
        let kp = generate_keypair().expect("keygen");
        let enc = encapsulate(&kp.encapsulation_key).expect("encap");
        let recovered = decapsulate(&kp.decapsulation_key, &enc.ciphertext).expect("decap");
        assert_eq!(enc.shared_secret.expose(), recovered.expose());
    }

    #[test]
    fn decap_with_wrong_key_yields_different_secret() {
        // ML-KEM implicit rejection: decap with the wrong key still
        // succeeds but produces a different shared secret. Validate
        // that mismatched calls cannot agree.
        let kp_a = generate_keypair().expect("keygen a");
        let kp_b = generate_keypair().expect("keygen b");
        let enc_to_a = encapsulate(&kp_a.encapsulation_key).expect("encap to a");
        let wrong = decapsulate(&kp_b.decapsulation_key, &enc_to_a.ciphertext)
            .expect("decap with wrong dk");
        assert_ne!(enc_to_a.shared_secret.expose(), wrong.expose());
    }

    #[test]
    fn encap_rejects_malformed_ek() {
        let bad = vec![0u8; 100];
        assert!(matches!(encapsulate(&bad), Err(MediaError::PqKex(_))));
    }

    #[test]
    fn decap_rejects_malformed_dk() {
        let kp = generate_keypair().expect("keygen");
        let enc = encapsulate(&kp.encapsulation_key).expect("encap");
        let bad_dk = vec![0u8; 100];
        assert!(matches!(
            decapsulate(&bad_dk, &enc.ciphertext),
            Err(MediaError::PqKex(_))
        ));
    }

    #[test]
    fn decap_rejects_malformed_ciphertext() {
        let kp = generate_keypair().expect("keygen");
        let bad_ct = vec![0u8; 100];
        assert!(matches!(
            decapsulate(&kp.decapsulation_key, &bad_ct),
            Err(MediaError::PqKex(_))
        ));
    }

    #[test]
    fn deterministic_from_seeded_rng() {
        let mut rng1 = rand_chacha::ChaCha20Rng::from_seed([42u8; 32]);
        let mut rng2 = rand_chacha::ChaCha20Rng::from_seed([42u8; 32]);
        let kp1 = generate_keypair_from_rng(&mut rng1).expect("keygen 1");
        let kp2 = generate_keypair_from_rng(&mut rng2).expect("keygen 2");
        assert_eq!(kp1.encapsulation_key, kp2.encapsulation_key);
        assert_eq!(kp1.decapsulation_key, kp2.decapsulation_key);
    }

    /// Test double for `dtls::state::State` — returns a fixed-bytes
    /// exporter so we can exercise [`extract_dtls_exporter`] without
    /// standing up a real DTLS handshake. Production callers pass a
    /// real `State` cloned from `DTLSConn::connection_state()`.
    struct FakeExporter {
        body: u8,
        len: usize,
    }

    #[async_trait]
    impl Kme for FakeExporter {
        async fn export_keying_material(
            &self,
            label: &str,
            context: &[u8],
            length: usize,
        ) -> Result<Vec<u8>, KeyingMaterialExporterError> {
            // Mirror what the real impl validates: empty context,
            // label not in the invalid-keying-labels list, length
            // matches our request.
            assert_eq!(label, DTLS_SRTP_EXPORTER_LABEL);
            assert!(context.is_empty());
            assert_eq!(length, self.len);
            Ok(vec![self.body; length])
        }
    }

    #[tokio::test]
    async fn extract_dtls_exporter_returns_60_bytes() {
        let exporter = FakeExporter {
            body: 0xab,
            len: DTLS_EXPORTER_LEN,
        };
        let out = extract_dtls_exporter(&exporter).await.expect("extract");
        assert_eq!(out.as_bytes(), &[0xabu8; DTLS_EXPORTER_LEN]);
    }

    /// A faulty exporter returning the wrong length must be rejected
    /// — guards against a future webrtc-rs API change silently
    /// changing the SRTP key layout from underneath us.
    struct WrongLenExporter;

    #[async_trait]
    impl Kme for WrongLenExporter {
        async fn export_keying_material(
            &self,
            _label: &str,
            _context: &[u8],
            _length: usize,
        ) -> Result<Vec<u8>, KeyingMaterialExporterError> {
            Ok(vec![0u8; 32]) // wrong: should be 60
        }
    }

    #[tokio::test]
    async fn extract_dtls_exporter_rejects_wrong_length() {
        let exporter = WrongLenExporter;
        let result = extract_dtls_exporter(&exporter).await;
        assert!(matches!(result, Err(MediaError::DtlsHandshake(_))));
    }
}
